### ISSUE TITLE
How much time does the model take to do inference for a single sample/individual?

### ISSUE THREAD

**Issue by tanziqi1234** [ustunb/actionable-recourse#13]
I am considering applying your tool to solve more complicated problems(more complicated inputs and models), but I worry about the time and spatial complexity.
So I wonder that,  in your experiments, if given one case of input and the linear classifier gets a negative output, how much time and memory does it need to solve the integer programming and give the flipset? Does it take a very long time and very much memory? And how about a large number of cases?

**Comment by ustunb** [comment]
Hello!

Some answers

- In our experiments, it takes <1 second to setup and solve the MIP. This allows you to produce a single action item in a flipset and to check that the point has some recourse. It takes around the same time to populate the flipset with additional action items.

- The audits take longer since we need to setup and solve the IP over all points that receive a negative prediction. If there are n such points, then the audit process should take ~n seconds.

- Memory isn't an issue.

- These results are when using the CPLEX solver on a 2015 MBP with 16 GB of RAM. It might be slightly slower with the open source solver.

Hope this helps!

On Wed, Dec 4, 2019 at 8:21 AM tanziqi1234 <notifications@github.com<mailto:notifications@github.com>> wrote:

I am considering applying your tool to solve more complicated problems(more complicated inputs and models), but I worry about the time and spatial complexity.
So I wonder that, in your experiments, if given one case of input and the linear classifier gets a negative output, how much time and memory does it need to solve the integer programming and give the flipset? Does it take a very long time and very much memory? And how about a large number of cases?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ustunb_actionable-2Drecourse_issues_13-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DABM4UCNQLUYTFQA4VVDNKOLQW6VG3A5CNFSM4JVIROJ2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4H6ACK7Q&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=eB_oRo404IL7R_uIoh5wjffvGNzbFPBTaB7jG1xZ3Ck&m=fKt8-KLZfY6V1D35lVxKoySA9AWxkJXzS6wnTlgLkr4&s=_zHII4dqYMWVme8TfjXhVUxQ6AdsEpnwO0T3EP21T6Y&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABM4UCIVVJZQ455TOQMJEPDQW6VG3ANCNFSM4JVIROJQ&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=eB_oRo404IL7R_uIoh5wjffvGNzbFPBTaB7jG1xZ3Ck&m=fKt8-KLZfY6V1D35lVxKoySA9AWxkJXzS6wnTlgLkr4&s=8c1sXpJ44KzQTSA39z1yqCYmaaPpKdp2LTOOtQ_F-7g&e=>.

--
Berk Ustun, PhD
Postdoctoral Fellow, Center for Research on Computation for Society
Harvard John A. Paulson School of Engineering and Applied Sciences
http://www.berkustun.com <http://www.berkustun.com>

**Comment by tanziqi1234** [comment]
That's very helpful! 
Thank you very much!
